export type ExerciseSeed = { name: string; category: string };

// A large, global exercise library available to every user.
export const EXERCISE_LIBRARY: ExerciseSeed[] = [
  // Chest
  { name: "Barbell Bench Press", category: "Chest" },
  { name: "Incline Barbell Bench Press", category: "Chest" },
  { name: "Decline Bench Press", category: "Chest" },
  { name: "Dumbbell Bench Press", category: "Chest" },
  { name: "Incline Dumbbell Press", category: "Chest" },
  { name: "Dumbbell Fly", category: "Chest" },
  { name: "Cable Fly", category: "Chest" },
  { name: "Pec Deck", category: "Chest" },
  { name: "Push-Up", category: "Chest" },
  { name: "Chest Dip", category: "Chest" },
  { name: "Cable Crossover", category: "Chest" },
  { name: "Landmine Press", category: "Chest" },
  { name: "Floor Press", category: "Chest" },
  { name: "Smith Machine Bench Press", category: "Chest" },
  { name: "Weighted Dip", category: "Chest" },

  // Back
  { name: "Conventional Deadlift", category: "Back" },
  { name: "Pull-Up", category: "Back" },
  { name: "Chin-Up", category: "Back" },
  { name: "Lat Pulldown", category: "Back" },
  { name: "Barbell Row", category: "Back" },
  { name: "Dumbbell Row", category: "Back" },
  { name: "Seated Cable Row", category: "Back" },
  { name: "T-Bar Row", category: "Back" },
  { name: "Pendlay Row", category: "Back" },
  { name: "Single-Arm Cable Row", category: "Back" },
  { name: "Straight-Arm Pulldown", category: "Back" },
  { name: "Face Pull", category: "Back" },
  { name: "Rack Pull", category: "Back" },
  { name: "Good Morning", category: "Back" },
  { name: "Inverted Row", category: "Back" },
  { name: "Close-Grip Lat Pulldown", category: "Back" },

  // Shoulders
  { name: "Overhead Press", category: "Shoulders" },
  { name: "Seated Dumbbell Press", category: "Shoulders" },
  { name: "Arnold Press", category: "Shoulders" },
  { name: "Dumbbell Lateral Raise", category: "Shoulders" },
  { name: "Front Raise", category: "Shoulders" },
  { name: "Rear Delt Fly", category: "Shoulders" },
  { name: "Upright Row", category: "Shoulders" },
  { name: "Push Press", category: "Shoulders" },
  { name: "Cable Lateral Raise", category: "Shoulders" },
  { name: "Machine Shoulder Press", category: "Shoulders" },
  { name: "Dumbbell Shrug", category: "Shoulders" },

  // Arms
  { name: "Barbell Curl", category: "Arms" },
  { name: "Dumbbell Curl", category: "Arms" },
  { name: "Hammer Curl", category: "Arms" },
  { name: "Preacher Curl", category: "Arms" },
  { name: "Incline Dumbbell Curl", category: "Arms" },
  { name: "Cable Curl", category: "Arms" },
  { name: "Concentration Curl", category: "Arms" },
  { name: "EZ-Bar Curl", category: "Arms" },
  { name: "Spider Curl", category: "Arms" },
  { name: "Close-Grip Bench Press", category: "Arms" },
  { name: "Triceps Pushdown", category: "Arms" },
  { name: "Overhead Triceps Extension", category: "Arms" },
  { name: "Skull Crusher", category: "Arms" },
  { name: "Triceps Dip", category: "Arms" },
  { name: "Diamond Push-Up", category: "Arms" },
  { name: "Rope Pushdown", category: "Arms" },
  { name: "Triceps Kickback", category: "Arms" },

  // Legs
  { name: "Back Squat", category: "Legs" },
  { name: "Front Squat", category: "Legs" },
  { name: "Leg Press", category: "Legs" },
  { name: "Hack Squat", category: "Legs" },
  { name: "Leg Extension", category: "Legs" },
  { name: "Bulgarian Split Squat", category: "Legs" },
  { name: "Walking Lunge", category: "Legs" },
  { name: "Goblet Squat", category: "Legs" },
  { name: "Step-Up", category: "Legs" },
  { name: "Sissy Squat", category: "Legs" },
  { name: "Pistol Squat", category: "Legs" },
  { name: "Romanian Deadlift", category: "Legs" },
  { name: "Stiff-Leg Deadlift", category: "Legs" },
  { name: "Lying Leg Curl", category: "Legs" },
  { name: "Seated Leg Curl", category: "Legs" },
  { name: "Nordic Hamstring Curl", category: "Legs" },
  { name: "Glute-Ham Raise", category: "Legs" },
  { name: "Single-Leg Romanian Deadlift", category: "Legs" },

  // Glutes
  { name: "Barbell Hip Thrust", category: "Glutes" },
  { name: "Glute Bridge", category: "Glutes" },
  { name: "Cable Kickback", category: "Glutes" },
  { name: "Sumo Deadlift", category: "Glutes" },
  { name: "Curtsy Lunge", category: "Glutes" },
  { name: "Donkey Kick", category: "Glutes" },

  // Calves
  { name: "Standing Calf Raise", category: "Calves" },
  { name: "Seated Calf Raise", category: "Calves" },
  { name: "Calf Press", category: "Calves" },
  { name: "Single-Leg Calf Raise", category: "Calves" },

  // Core
  { name: "Plank", category: "Core" },
  { name: "Crunch", category: "Core" },
  { name: "Hanging Leg Raise", category: "Core" },
  { name: "Cable Crunch", category: "Core" },
  { name: "Russian Twist", category: "Core" },
  { name: "Ab Wheel Rollout", category: "Core" },
  { name: "Mountain Climber", category: "Core" },
  { name: "Side Plank", category: "Core" },
  { name: "Dead Bug", category: "Core" },
  { name: "Toes to Bar", category: "Core" },
  { name: "Bicycle Crunch", category: "Core" },

  // Cardio
  { name: "Treadmill Run", category: "Cardio" },
  { name: "Stationary Bike", category: "Cardio" },
  { name: "Rowing Machine", category: "Cardio" },
  { name: "Stair Climber", category: "Cardio" },
  { name: "Jump Rope", category: "Cardio" },
  { name: "Sled Push", category: "Cardio" },
  { name: "Battle Ropes", category: "Cardio" },
  { name: "Assault Bike", category: "Cardio" },

  // Full Body
  { name: "Clean and Press", category: "Full Body" },
  { name: "Snatch", category: "Full Body" },
  { name: "Thruster", category: "Full Body" },
  { name: "Kettlebell Swing", category: "Full Body" },
  { name: "Burpee", category: "Full Body" },
  { name: "Turkish Get-Up", category: "Full Body" },
  { name: "Farmer's Walk", category: "Full Body" },

  // Forearms
  { name: "Wrist Curl", category: "Forearms" },
  { name: "Reverse Wrist Curl", category: "Forearms" },
  { name: "Plate Pinch", category: "Forearms" },
];
